sudo: required

services:
  - docker

language: node_js

node_js:
  - '9'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker-compose -f e2e/docker-compose.yml down -v
  - docker-compose -f e2e/docker-compose.yml build

script:
  - yarn ci-check
  - docker-compose -f e2e/docker-compose.yml run test ./tasks/installs.sh
